name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "sreenivas98"
          git config --global user.email "srivatsava.sai@gmail.com"

      - name: Deploy
        run: |
          npm install -g gh-pages
          gh-pages -d build -b gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
