name: Build and Deploy React App

on:
  push:
    branches:
      - main
    # You can also trigger the workflow on pull request merge if needed
    # pull_request:
    #   types: [closed]
    #   branches:
    #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or whichever version you are using

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy
        run: |
          npm install -g gh-pages
          gh-pages -d build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necessary for deploying to GitHub Pages
